/*
* Michael Mongelli
* CSC315
* Stage VI
* 
* Initialize database tables and 
* populate it with Trentoniana data
* provided in CSVs (named by the table they populate)
* using psql.
*/

DROP DATABASE IF EXISTS trentoniana;
CREATE DATABASE trentoniana;
\c trentoniana

-- MAX LENGTH OF URL STRING: 2083

-- INITIALIZE TABLES AND FOREIGN KEY REFERENCES

-- TRENTONIANA DATA
CREATE TABLE SYNOPSIS(file_id VARCHAR(2083) NOT NULL PRIMARY KEY);
CREATE TABLE TRANSCRIPT(file_id VARCHAR(2083) NOT NULL PRIMARY KEY);
CREATE TABLE AUDIO(file_id VARCHAR(2083) NOT NULL PRIMARY KEY, date_of_recording DATE);
CREATE TABLE PARTICIPANT(
    fullname VARCHAR(255) NOT NULL, 
    audio VARCHAR(2083) NOT NULL FOREIGN KEY REFERENCES AUDIO(file_id)
);
CREATE TABLE ENTRY(
    entry_id VARCHAR(255) NOT NULL PRIMARY KEY,
    audio VARCHAR(2083) NOT NULL FOREIGN KEY REFERENCES AUDIO(file_id),
    transcript VARCHAR(2083) FOREIGN KEY REFERENCES TRANSCRIPT(file_id),
    synopsis VARCHAR(2083) FOREIGN KEY REFERENCES SYNOPSIS(file_id)
);
CREATE TABLE TOPIC(
    topic VARCHAR(255) NOT NULL, 
    entry VARCHAR(255) NOT NULL FOREIGN KEY REFERENCES ENTRY(entry_id)
);

-- ACCOUNTS
CREATE TABLE ADMIN(
    username VARCHAR(255) NOT NULL PRIMARY KEY, 
    password VARCHAR(255) NOT NULL
);
CREATE TABLE EDITOR(
    username VARCHAR(255) NOT NULL PRIMARY KEY, 
    password VARCHAR(255) NOT NULL,
    admin VARCHAR(255) FOREIGN KEY REFERENCES ADMIN(username)
);